/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-10 16:51:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>MediSol</title>\r\n");
      out.write("  <link rel=\"icon\" href=\"resources/medisol.png\" />\r\n");
      out.write("\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js\" integrity=\"sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/js/bootstrap.min.js\" integrity=\"sha512-7rusk8kGPFynZWu26OKbTeI+QPoYchtxsmPeBqkHIEXJxeun4yJ4ISYe7C6sz9wdxeE1Gk3VxsIWgCZTc+vX3g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/css/bootstrap.min.css\" integrity=\"sha512-rt/SrQ4UNIaGfDyEXZtNcyWvQeOq0QLygHluFQcSjaGB04IxWhal71tKuzP6K8eYXYB6vJV4pHkXcmFGGQ1/0w==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- font awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css\" integrity=\"sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/all.min.js\" integrity=\"sha512-naukR7I+Nk6gp7p5TMA4ycgfxaZBJ7MO5iC3Fp6ySQyKFHOGfpkSZkYVWV5R7u7cfAicxanwYQ5D1e17EfJcMA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Lightbox CSS & Script -->\r\n");
      out.write("  <script src=\"resources/lightbox/ekko-lightbox.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/lightbox/ekko-lightbox.css\"/>\r\n");
      out.write("  <!-- Lightbox END -->\r\n");
      out.write("\r\n");
      out.write("  <!-- AOS CSS & Script -->\r\n");
      out.write("  <script src=\"resources/aos/aos.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/aos/aos.css\"/>\r\n");
      out.write("  <!-- AOS END -->\r\n");
      out.write("\r\n");
      out.write("  <!-- custom css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/custom.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

		String m=(String)session.getAttribute("msg");
		if(m!=null){
			if(m.contains("success")){
			
      out.write("\r\n");
      out.write("				<h6 class=\"bg-success text-white text-center p-3\">");
      out.print(m );
      out.write("</h6>\r\n");
      out.write("			");
 
				session.setAttribute("msg", null);
			}else if(m.contains("failed") || m.contains("Already")){
			
      out.write("\r\n");
      out.write("				<h6 class=\"bg-danger text-white text-center p-3\">");
      out.print(m );
      out.write("</h6>\r\n");
      out.write("			");
 
				session.setAttribute("msg", null);
			}else {
			
      out.write("\r\n");
      out.write("				<h6 class=\"bg-warning text-center p-3\">");
      out.print(m );
      out.write("</h6>\r\n");
      out.write("			");
 
				session.setAttribute("msg", null);
			}
		}
	
      out.write("\r\n");
      out.write("  <p class=\"text-center bg-light p-2\">For any emergency contact <a href=\"tel:9811XXXXXX\">9811XXXXXX</a> or email at <a href=\"mailto:info@plusdemic.com\">info@medisol.com</a> </p>\r\n");
      out.write("  <nav class=\"navbar navbar-expand-sm container\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("        <img src=\"resources/medisol.png\" alt=\"\"/> <span>Medi</span>Sol\r\n");
      out.write("      </a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#my-navbar\"><i class=\"fa-solid fa-bars\"></i></button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"my-navbar\">\r\n");
      out.write("          <ul class=\"navbar-nav  mx-auto\">\r\n");
      out.write("            <li>\r\n");
      out.write("              <a class=\"nav-link\" href=\"index.jsp\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a class=\"nav-link\" href=\"UserLogin.jsp\">User Sign-In/Sign-Up</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <button class=\"btn btn-light\" data-toggle=\"modal\" data-target=\"#myModal\">Admin Login</button>\r\n");
      out.write("      </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <header class=\"container mt-4\">\r\n");
      out.write("  	  <div class=\"p-2\">\r\n");
      out.write("        <form action=\"SearchItems.jsp\" method=\"post\" >\r\n");
      out.write("          <div class=\"form-row\">\r\n");
      out.write("		    <div class=\"col-10\">\r\n");
      out.write("		      <input class=\"form-control\" type=\"text\" name=\"name\" maxlength=\"100\" placeholder=\"Medicine name/Product name\" required/>\r\n");
      out.write("		    </div>\r\n");
      out.write("		    <div class=\"col-2\">\r\n");
      out.write("		      <button type=\"submit\" class=\"btn btn-success\">Search</button>\r\n");
      out.write("		    </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("        </form>\r\n");
      out.write("  	  </div>\r\n");
      out.write("      <div class=\"row p-5\">\r\n");
      out.write("          <div class=\"col-sm\"  data-aos=\"zoom-in\" data-aos-duration=\"2000\" >\r\n");
      out.write("              <h1>Covid-19 Risk Assessment</h1>\r\n");
      out.write("              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa ipsa totam omnis nesciunt praesentium minus officia eligendi dicta nam, nobis quod, nostrum enim. Quaerat, fuga blanditiis! Repellat est impedit at eligendi tenetur. Repudiandae perferendis sit doloremque blanditiis eum? Tenetur voluptatum similique neque non iste, error expedita suscipit? Commodi, delectus. Repellat!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm\"  data-aos=\"fade-left\" data-aos-duration=\"2000\" >\r\n");
      out.write("              <img src=\"resources/img1.jpg\" alt=\"\">\r\n");
      out.write("              <img src=\"resources/img2.jpg\" alt=\"\">\r\n");
      out.write("              <img src=\"resources/img3.jpg\" alt=\"\">\r\n");
      out.write("              <img src=\"resources/img4.jpg\" alt=\"\">\r\n");
      out.write("              <img src=\"resources/img5.jpg\" alt=\"\">\r\n");
      out.write("              <img src=\"resources/img6.jpg\" alt=\"\">\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <section class=\"container mt-4 p-4\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-sm-8\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm my-2\">\r\n");
      out.write("                <div class=\"mycard\">\r\n");
      out.write("                  <div class=\"image-circle\">\r\n");
      out.write("                    <img src=\"resources/icon1.png\" alt=\"\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h5>Triage</h5>\r\n");
      out.write("                  <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsam, laudantium.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm my-2\">\r\n");
      out.write("              <div class=\"mycard\">\r\n");
      out.write("                <div class=\"image-circle\">\r\n");
      out.write("                  <img src=\"resources/icon2.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h5>Triage</h5>\r\n");
      out.write("                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsam, laudantium.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm my-2\">\r\n");
      out.write("            <div class=\"mycard\">\r\n");
      out.write("              <div class=\"image-circle\">\r\n");
      out.write("                <img src=\"resources/icon3.png\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <h5>Triage</h5>\r\n");
      out.write("              <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsam, laudantium.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-4\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <h3>How it helps people</h3>\r\n");
      out.write("            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum at aspernatur, fugit asperiores voluptatem mollitia expedita repellat cumque iusto! Quaerat numquam saepe voluptas vitae, aliquam eligendi tenetur quibusdam harum quasi in culpa, ipsam consequatur modi iusto iure earum corporis excepturi inventore cum officiis. Adipisci eos necessitatibus quidem voluptatem fugiat porro.</p>\r\n");
      out.write("            <button class=\"btn btn-light\" data-toggle=\"modal\" data-target=\"#myModal\">Get in touch</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <section>\r\n");
      out.write("    <div id=\"carouselExampleControls\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("      <div class=\"carousel-inner\">\r\n");
      out.write("        <div class=\"carousel-item active\">\r\n");
      out.write("          <img src=\"resources/slide1.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\">\r\n");
      out.write("          <img src=\"resources/slide2.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\">\r\n");
      out.write("          <img src=\"resources/slide3.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("     <button class=\"carousel-control-prev\" type=\"button\" data-target=\"#carouselExampleControls\" data-slide=\"prev\">\r\n");
      out.write("        <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"sr-only\">Previous</span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <button class=\"carousel-control-next\" type=\"button\" data-target=\"#carouselExampleControls\" data-slide=\"next\">\r\n");
      out.write("        <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"sr-only\">Next</span>\r\n");
      out.write("      </button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <hr>\r\n");
      out.write("  <section class=\"container\" id=\"service\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-sm m-2\"  data-aos=\"fade-up\" data-aos-duration=\"1000\" data-aos-delay=\"100\" >\r\n");
      out.write("          <h3>How to use it</h3>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum at aspernatur, fugit asperiores voluptatem mollitia expedita repellat cumque iusto! Quaerat numquam saepe voluptas vitae, aliquam eligendi tenetur quibusdam harum quasi in culpa, ipsam consequatur modi iusto iure earum corporis excepturi inventore cum officiis. Adipisci eos necessitatibus quidem voluptatem fugiat porro.</p>\r\n");
      out.write("          <button class=\"btn btn-light\" data-toggle=\"modal\" data-target=\"#myModal\">Get in touch</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm m-2 text-center\"  data-aos=\"fade-up\" data-aos-duration=\"1000\" data-aos-delay=\"400\" >\r\n");
      out.write("          <img src=\"resources/image1.jpg\" class=\"rounded-lg img-fluid\" alt=\"\">\r\n");
      out.write("          <h6 class=\"p-2 text-muted\">Coronavirus</h6>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm m-2 text-center\" data-aos=\"fade-up\" data-aos-duration=\"1000\" data-aos-delay=\"700\"  >\r\n");
      out.write("          <img src=\"resources/image2.jpg\" class=\"rounded-lg img-fluid\" height=\"250px\" alt=\"\">\r\n");
      out.write("          <h6 class=\"p-2 text-muted\">Diagnostic</h6>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm m-2 text-center\" data-aos=\"fade-up\" data-aos-duration=\"1000\" data-aos-delay=\"1000\"  >\r\n");
      out.write("          <img src=\"resources/image3.jpg\" class=\"rounded-lg img-fluid\" height=\"250px\" alt=\"\">\r\n");
      out.write("          <h6 class=\"p-2 text-muted\">Test</h6>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <section class=\"container-fluid bg-info p-5 text-center\">\r\n");
      out.write("      <div class=\"container gallery\">\r\n");
      out.write("        <a href=\"resources/img1.jpg\" data-toggle=\"lightbox\" data-gallery=\"my-gallery\"><img src=\"resources/img1.jpg\" alt=\"\"/></a>\r\n");
      out.write("        <a href=\"resources/img2.jpg\" data-toggle=\"lightbox\" data-gallery=\"my-gallery\"><img src=\"resources/img2.jpg\" alt=\"\"/></a>\r\n");
      out.write("        <a href=\"resources/img3.jpg\" data-toggle=\"lightbox\" data-gallery=\"my-gallery\"><img src=\"resources/img3.jpg\" alt=\"\"/></a>\r\n");
      out.write("        <a href=\"resources/img4.jpg\" data-toggle=\"lightbox\" data-gallery=\"my-gallery\"><img src=\"resources/img4.jpg\" alt=\"\"/></a>\r\n");
      out.write("        <a href=\"resources/img5.jpg\" data-toggle=\"lightbox\" data-gallery=\"my-gallery\"><img src=\"resources/img5.jpg\" alt=\"\"/></a>\r\n");
      out.write("        <a href=\"resources/img6.jpg\" data-toggle=\"lightbox\" data-gallery=\"my-gallery\"><img src=\"resources/img6.jpg\" alt=\"\"/></a>\r\n");
      out.write("      </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <section class=\"container bg-light my-4 p-5 text-center\" >\r\n");
      out.write("      <h3 data-aos=\"zoom-out\" data-aos-duration=\"1000\" data-aos-delay=\"100\">Why you can trust this tool</h3>\r\n");
      out.write("      <div class=\"row container m-5\" data-aos=\"zoom-out\" data-aos-duration=\"1000\" data-aos-delay=\"500\">\r\n");
      out.write("        <div class=\"col-sm\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-2 text-right\">\r\n");
      out.write("                <img src=\"resources/icon1.png\" height=\"50px\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-10 text-left\">\r\n");
      out.write("              <h5>Lorem ipsum dolor sit amet, consectetur adipisicing.</h5>\r\n");
      out.write("              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem unde et eveniet.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-2 text-right\">\r\n");
      out.write("                <img src=\"resources/icon2.png\" height=\"50px\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-10 text-left\">\r\n");
      out.write("              <h5>Lorem ipsum dolor sit amet, consectetur adipisicing.</h5>\r\n");
      out.write("              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem unde et eveniet.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>  \r\n");
      out.write("  </section>\r\n");
      out.write("  <footer class=\"container m-5\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-sm m-2 text-left\">\r\n");
      out.write("        <img src=\"resources/medisol.png\" height=\"20px\" alt=\"\"/> <span class=\"text-danger\"><b>Medi</b></span>Sol\r\n");
      out.write("        <p>\r\n");
      out.write("          Lorem ipsum dolor sit amet consectetur.\r\n");
      out.write("          <br>\r\n");
      out.write("          Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm m-2 text-right\">\r\n");
      out.write("        <p>\r\n");
      out.write("          <a class=\"m-2\" href=\"http://www.facebook.com/incapp\" target=\"_blank\"><i class=\"fa-brands fa-facebook-f fa-2x\"></i></a>\r\n");
      out.write("          <a class=\"m-2\" href=\"http://www.instagram.com/incapp.in\" target=\"_blank\"><i class=\"fa-brands fa-instagram fa-2x\"></i></a>\r\n");
      out.write("          <a class=\"m-2\" href=\"http://www.youtube.com/incapp\" target=\"_blank\"><i class=\"fa-brands fa-youtube fa-2x\"></i></a>\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  <a id=\"btnTop\"><i class=\"fa-solid fa-circle-up fa-2x\"></i></a>\r\n");
      out.write("  <!-- Modal -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header bg-info\">\r\n");
      out.write("          <h5 class=\"modal-title text-white\" id=\"exampleModalLabel\">Admin Login Form</h5>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("            <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("          <form action=\"AdminLogin\" method=\"post\" >\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <input type=\"text\" name=\"id\" maxlength=\"100\" class=\"form-control\" placeholder=\"Admin ID\" required/>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <input type=\"password\"name=\"password\" maxlength=\"20\" class=\"form-control\" placeholder=\"Admin Password\" required/>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\">Login</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("  //AOS\r\n");
      out.write("  AOS.init();\r\n");
      out.write("\r\n");
      out.write("  //script for scroll to top\r\n");
      out.write("  $(\"#btnTop\").click(function () {\r\n");
      out.write("        $(\"html, body\").animate({scrollTop: 0}, 1000);\r\n");
      out.write("    });\r\n");
      out.write("  //script for scroll to Service Section\r\n");
      out.write("  $(\"#service-menu\").click(function () {\r\n");
      out.write("      document.getElementById(\"service\").scrollIntoView({behavior: 'smooth'});\r\n");
      out.write("    });\r\n");
      out.write("  //script for light box\r\n");
      out.write("  $(document).on('click', '[data-toggle=\"lightbox\"]', function(event) {\r\n");
      out.write("      event.preventDefault();\r\n");
      out.write("      $(this).ekkoLightbox();\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
