/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-10 16:51:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>MediSol</title>\r\n");
      out.write("  <link rel=\"icon\" href=\"resources/medisol.png\" />\r\n");
      out.write("\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js\" integrity=\"sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/js/bootstrap.min.js\" integrity=\"sha512-7rusk8kGPFynZWu26OKbTeI+QPoYchtxsmPeBqkHIEXJxeun4yJ4ISYe7C6sz9wdxeE1Gk3VxsIWgCZTc+vX3g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/css/bootstrap.min.css\" integrity=\"sha512-rt/SrQ4UNIaGfDyEXZtNcyWvQeOq0QLygHluFQcSjaGB04IxWhal71tKuzP6K8eYXYB6vJV4pHkXcmFGGQ1/0w==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- font awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css\" integrity=\"sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/all.min.js\" integrity=\"sha512-naukR7I+Nk6gp7p5TMA4ycgfxaZBJ7MO5iC3Fp6ySQyKFHOGfpkSZkYVWV5R7u7cfAicxanwYQ5D1e17EfJcMA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Lightbox CSS & Script -->\r\n");
      out.write("  <script src=\"resources/lightbox/ekko-lightbox.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/lightbox/ekko-lightbox.css\"/>\r\n");
      out.write("  <!-- Lightbox END -->\r\n");
      out.write("\r\n");
      out.write("  <!-- AOS CSS & Script -->\r\n");
      out.write("  <script src=\"resources/aos/aos.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/aos/aos.css\"/>\r\n");
      out.write("  <!-- AOS END -->\r\n");
      out.write("\r\n");
      out.write("  <!-- custom css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/custom.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

		String m=(String)session.getAttribute("msg");
		if(m!=null){
			
      out.write("\r\n");
      out.write("				<h6 class=\"bg-danger text-white text-center p-3\">");
      out.print(m );
      out.write("</h6>\r\n");
      out.write("			");
 
			session.setAttribute("msg", null);
		}
	
      out.write("\r\n");
      out.write("  <p class=\"text-center bg-light p-2\">For any emergency contact <a href=\"tel:9811XXXXXX\">9811XXXXXX</a> or email at <a href=\"mailto:info@plusdemic.com\">info@medisol.com</a> </p>\r\n");
      out.write("  <nav class=\"navbar navbar-expand-sm container\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("        <img src=\"resources/medisol.png\" alt=\"\"/> <span>Medi</span>Sol\r\n");
      out.write("      </a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#my-navbar\"><i class=\"fa-solid fa-bars\"></i></button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"my-navbar\">\r\n");
      out.write("          <ul class=\"navbar-nav  mx-auto\">\r\n");
      out.write("            <li>\r\n");
      out.write("              <a class=\"nav-link\" href=\"index.jsp\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a class=\"nav-link\" href=\"UserLogin.jsp\">User Sign-In/Sign-Up</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          \r\n");
      out.write("      </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <section class=\"container-fluid bg-secondary mt-4 p-5\">\r\n");
      out.write("    	<div class='row'>\r\n");
      out.write("    		<div class='col-sm m-4'>\r\n");
      out.write("    			<div>\r\n");
      out.write("	    			<h3 class='text-white'>User Sign-In</h3>\r\n");
      out.write("	    			<hr/>\r\n");
      out.write("	    			<form action=\"UserLogin\" method=\"post\" >\r\n");
      out.write("			            <div class=\"form-group\">\r\n");
      out.write("			              <input type=\"text\" name=\"email\" maxlength=\"100\" class=\"form-control\" placeholder=\"User Email\" required/>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"form-group\">\r\n");
      out.write("			              <input type=\"password\"name=\"password\" maxlength=\"20\" class=\"form-control\" placeholder=\"User Password\" required/>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <button type=\"submit\" class=\"btn btn-primary\">Login</button>\r\n");
      out.write("			        </form>\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    		<div class='col-sm m-4'>\r\n");
      out.write("    			<div>\r\n");
      out.write("	    			<h3 class='text-white'>User Sign-Up</h3>\r\n");
      out.write("	    			<hr/>\r\n");
      out.write("	    			<form action=\"UserRegister\" method=\"post\" >\r\n");
      out.write("			            <div class=\"form-group\">\r\n");
      out.write("			              <input type=\"email\" name=\"email\" maxlength=\"100\" class=\"form-control\" placeholder=\"User Email\" required/>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"form-group\">\r\n");
      out.write("			              <input type=\"text\" name=\"name\" pattern=\"[a-zA-Z ]+\" maxlength=\"50\" class=\"form-control\" placeholder=\"User Name\" required/>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"form-group\">\r\n");
      out.write("			              <input type=\"tel\" name=\"phone\" pattern=\"[0-9]+\" maxlength=\"10\" class=\"form-control\" placeholder=\"User Phone\" required/>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"form-group\">\r\n");
      out.write("			              <input type=\"password\"name=\"password\" maxlength=\"20\" class=\"form-control\" placeholder=\"User Password\" required/>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <button type=\"submit\" class=\"btn btn-primary\">Register</button>\r\n");
      out.write("			        </form>\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    	</div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <footer class=\"container m-5\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-sm m-2 text-left\">\r\n");
      out.write("        <img src=\"resources/medisol.png\" height=\"20px\" alt=\"\"/> <span class=\"text-danger\"><b>Medi</b></span>Sol\r\n");
      out.write("        <p>\r\n");
      out.write("          Lorem ipsum dolor sit amet consectetur.\r\n");
      out.write("          <br>\r\n");
      out.write("          Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm m-2 text-right\">\r\n");
      out.write("        <p>\r\n");
      out.write("          <a class=\"m-2\" href=\"http://www.facebook.com/incapp\" target=\"_blank\"><i class=\"fa-brands fa-facebook-f fa-2x\"></i></a>\r\n");
      out.write("          <a class=\"m-2\" href=\"http://www.instagram.com/incapp.in\" target=\"_blank\"><i class=\"fa-brands fa-instagram fa-2x\"></i></a>\r\n");
      out.write("          <a class=\"m-2\" href=\"http://www.youtube.com/incapp\" target=\"_blank\"><i class=\"fa-brands fa-youtube fa-2x\"></i></a>\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  <a id=\"btnTop\"><i class=\"fa-solid fa-circle-up fa-2x\"></i></a>\r\n");
      out.write("  <!-- Modal -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header bg-info\">\r\n");
      out.write("          <h5 class=\"modal-title text-white\" id=\"exampleModalLabel\">Admin Login Form</h5>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("            <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("          <form action=\"AdminLogin\" method=\"post\" >\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <input type=\"text\" name=\"id\" maxlength=\"100\" class=\"form-control\" placeholder=\"Admin ID\" required/>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <input type=\"password\"name=\"password\" maxlength=\"20\" class=\"form-control\" placeholder=\"Admin Password\" required/>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\">Login</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("  //AOS\r\n");
      out.write("  AOS.init();\r\n");
      out.write("\r\n");
      out.write("  //script for scroll to top\r\n");
      out.write("  $(\"#btnTop\").click(function () {\r\n");
      out.write("        $(\"html, body\").animate({scrollTop: 0}, 1000);\r\n");
      out.write("    });\r\n");
      out.write("  //script for scroll to Service Section\r\n");
      out.write("  $(\"#service-menu\").click(function () {\r\n");
      out.write("      document.getElementById(\"service\").scrollIntoView({behavior: 'smooth'});\r\n");
      out.write("    });\r\n");
      out.write("  //script for light box\r\n");
      out.write("  $(document).on('click', '[data-toggle=\"lightbox\"]', function(event) {\r\n");
      out.write("      event.preventDefault();\r\n");
      out.write("      $(this).ekkoLightbox();\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
